-- ============================================================================
-- BARCHI FURNITURE — SUPABASE PUSH SUBSCRIPTION SCHEMA
-- Execute this SQL script in your Supabase SQL Editor to enable Web Push
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint TEXT NOT NULL,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Allow public read push_subscriptions" ON public.push_subscriptions;
DROP POLICY IF EXISTS "Allow public insert push_subscriptions" ON public.push_subscriptions;
DROP POLICY IF EXISTS "Allow public delete push_subscriptions" ON public.push_subscriptions;
DROP POLICY IF EXISTS "Allow public update push_subscriptions" ON public.push_subscriptions;

-- Create policies for public access (Anon key)
CREATE POLICY "Allow public read push_subscriptions" ON public.push_subscriptions FOR SELECT USING (true);
CREATE POLICY "Allow public insert push_subscriptions" ON public.push_subscriptions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete push_subscriptions" ON public.push_subscriptions FOR DELETE USING (true);
CREATE POLICY "Allow public update push_subscriptions" ON public.push_subscriptions FOR UPDATE USING (true);
